spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth-server
          uri: lb://AUTH-SERVER
          predicates:
            - Path=/api/auth/**

        - id: admin-service
          uri: lb://ADMIN-SERVICE
          predicates:
            - Path=/api/admin/**
          filters:
            - AuthenticationFilter

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/user/**
          filters:
            - AuthenticationFilter

        - id: post-service
          uri: lb://POST-SERVICE
          predicates:
            - Path=/api/post/**
          filters:
            - AuthenticationFilter
  main:
    web-application-type: reactive
server:
  port: 8000
#AUTH_SERVER_URL: "http://AUTH-SERVER//validate?token"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost