spring:
  application:
    name: post-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
#      DB_HOST=localhost;DB_NAME=hive_post;DB_USER=postgres;DB_PASSWORD=2248;
  servlet:
    multipart:
      enabled: true
      max-file-size: 205MB
      max-request-size: 205MB
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
server:
  port: 8081

FOLDER.PATH: "C:/Users/vishn/Projects/Hive-Second Project/post-service/src/main/resources/static/post-files/"