services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=hive
      - MONGO_INITDB_ROOT_PASSWORD=hive
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8282:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=hive
      - ME_CONFIG_MONGODB_ADMINPASSWORD=hive
      - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo: {}