server:
  port: 8083

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost

spring:
  application:
    name: chat-service
  data:
    mongodb:
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      host: ${DB_HOST}
      port: 27017
      database: ${DB_NAME}
      authentication-database: admin
#      DB_HOST=localhost;DB_NAME=hive_chat;DB_USER=hive;DB_PASSWORD=hive;