server:
  port: 8083
spring:
  application:
    name: chat-service
  data:
    mongodb:
      username: ${DB_USER}
      password: ${DB_PASSWORD}
      host: ${DB_HOST}
      port: 27017
      database: ${DB_NAME}
      authentication-database: admin